"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./utils/providers/reactQueryProvider";
import AuthProvider from "./utils/providers/authProvider";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "./components/theme-provider"


const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
			<ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
				<AuthProvider>
					<Navbar />
					<ReactQueryProvider>{children}</ReactQueryProvider>
				</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
